sudo: required
services:
  - docker

before_install:
  - docker build -t jcstorms/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jcstorms/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-816091408763"
  bucket_path: "docker-react"
  access_key_id: 
    secure: "$AWS_ACESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master